# Generated by Django 5.2 on 2025-04-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisrt_name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=40, verbose_name='Apellidos')),
                ('password', models.CharField(max_length=16, verbose_name='Contrsenia')),
            ],
        ),
    ]
