# Generated by Django 5.2 on 2025-04-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResgistroSesion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrobd',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
