# Generated by Django 5.2 on 2025-04-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResgistroSesion', '0002_rename_fisrt_name_registrobd_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrobd',
            name='confirmPaswword',
            field=models.CharField(default=1, max_length=16, verbose_name='ConfimarcionContraña'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrobd',
            name='email',
            field=models.CharField(default=1, max_length=20, verbose_name='Correo'),
            preserve_default=False,
        ),
    ]
